# Base image
#
FROM sles12:latest

# The author
MAINTAINER LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)

# Install the build dependencies
RUN zypper install -y \
  gcc-c++ \
  git \
  java-1_7_0-openjdk \
	python \
	python-setuptools \
	python-xml \
  make && \
	easy_install pip

RUN mkdir /tweet_updater
COPY tweety.py /tweet_updater/tweety.py
COPY searches.txt /tweet_updater/searches.txt
COPY requirements.txt /tweet_updater/requirements.txt
RUN pip install -r /tweet_updater/requirements.txt

#Expose port 8080 for app.js
EXPOSE 8080

#CMD /usr/sbin/sshd -D && /bin/bash && node /usr/local/timeseries/app.js
CMD python /tweet_updater/tweety.py 1000
