mongo_server:
    build: ../../sles12/mongo
    container_name: mongo_server

news_up:
    build: ../../sle12/news_feed_updater
    container_name: news_up
    links:
        - mongo_server

tweety_up:
    build: ../../sles12/tweet_updater
    container_name: tweety_up
    links:
        - mongo_server
    stdin_open: true
    tty: true

alchemy_api:
    build: ../../sles12/sentiment_alchemy
    container_name: alchemy_api
    ports:
    - "8081:8080"
    stdin_open: true
    tty: true

news_front:
    build: ../../sles12/news
    container_name: news_front
    ports:
    - "8083:8080"
    links:
        - alchemy_api
        - mongo_server
        - tweety_front #Since tweet frontend has the sentiment jar
    environment:
        - USE_ALCHEMY=yes

tweety_front:
    build: ../../sles12/tweets
    container_name: tweety_front
    ports:
    - "8082:8080"
    links:
        - alchemy_api
        - mongo_server
    environment:
        - USE_ALCHEMY=yes
