# Base image
FROM brunswickheads/clefos71-nodejs-s390x:latest

# The author
MAINTAINER LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)

# Install grunt-cli
CMD ["npm", "install", "-g", "grunt-cli"]
